# Generated by Django 3.2.4 on 2021-06-10 21:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PostVaga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('faixa_salarial', models.CharField(choices=[('1000', 'Até mil reais'), ('2000', 'Mil até 2 reais'), ('3000', '2 mil à 3 mil reais'), ('4000', 'Acima de 3 mil reais')], max_length=100)),
                ('requisitos', models.TextField()),
                ('escolaridade_min', models.CharField(choices=[('1', 'Ensino Fundamental'), ('2', 'Ensino Medio'), ('3', 'Tecnologo'), ('4', 'Ensino Superior'), ('5', 'Pós/MBA/Mestrado'), ('6', 'Doutorado')], max_length=50)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
