# Generated by Django 3.2.4 on 2021-06-13 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='escolaridade_min',
            field=models.CharField(choices=[('1', 'Ensino Fundamental'), ('2', 'Ensino Medio'), ('3', 'Tecnologo'), ('4', 'Ensino Superior'), ('5', 'Pós/MBA/Mestrado'), ('6', 'Doutorado')], default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='faixa_salarial',
            field=models.CharField(choices=[('1000', 'Até mil reais'), ('2000', 'Mil até 2 reais'), ('3000', '2 mil à 3 mil reais'), ('4000', 'Acima de 3 mil reais')], default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='escolaridade_min',
            field=models.CharField(choices=[('1', 'Ensino Fundamental'), ('2', 'Ensino Medio'), ('3', 'Tecnologo'), ('4', 'Ensino Superior'), ('5', 'Pós/MBA/Mestrado'), ('6', 'Doutorado')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='faixa_salarial',
            field=models.CharField(choices=[('1000', 'Até mil reais'), ('2000', 'Mil até 2 reais'), ('3000', '2 mil à 3 mil reais'), ('4000', 'Acima de 3 mil reais')], default=1, max_length=100),
            preserve_default=False,
        ),
    ]
